apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: backend
  serviceName: mongo
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:latest
        name: mongo
        value:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE 
          value: "/etc/mongo-credentials/MONGO_ROOT_USERNAME"
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE 
          value: "/etc/mongo-credentials/MONGO_ROOT_PASSWORD"
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: mongo-config
          mountPath: /config
        - name: mongo-pass
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
